### ISSUE TITLE
可以考虑添加太极支持吗？

### ISSUE THREAD

**Issue by PoisonBCat** [rhjdvsgsgks/VideoEnhancementPlus#1]
您好开发者，
希望能添加模块对太极的支持，十分感谢您的付出

**Comment by rhjdvsgsgks** [comment]
暂时不考虑，一是太极不开源，二是需要到太极自己的模块商店上认证才能使用
如果你没有 root 的话这种重新签名类的 xposed 框架是无法对系统应用生效的（重新签名后签名不同），如果已经 root 了的话更推荐开源的 edxposed

**Comment by PoisonBCat** [comment]
> 暂时不考虑，一是太极不开源，二是需要到太极自己的模块商店上认证才能使用
> 如果你没有 root 的话这种重新签名类的 xposed 框架是无法对系统应用生效的（重新签名后签名不同），如果已经 root 了的话更推荐开源的 edxposed

谢谢您的努力
手机已root，但是edxp不太符合个人需求，所以只能忍痛割爱，再次感谢
