### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [rhjdvsgsgks/VideoEnhancementPlus#2]
Can this xposed module work together with this magisk module using any phone!? Or not?!
Bravia Engine Magisk https://github.com/enggarsulistyo/BraviaEngine/releases/tag/v4.0.3

**Comment by rhjdvsgsgks** [comment]
1. i didn't find any whitelist limit in the magisk module
2. my xposed module hook the package `com.sonymobile.swiqisystemservice` which the magisk module don't have

**Comment by ghost** [comment]
@rhjdvsgsgks thanks for the quick reply :)
